#!/bin/bash
#
# aattd	Startup script for the Automate All The Things Server
#
# chkconfig: - 
# description: The Automate All The Things server is a central location for aatt endpoint reporting and state tracking
# processname: aattd
# config: /opt/aatt/etc/config.ini
# pidfile: /var/run/aatt/aattd.pid
#
### BEGIN INIT INFO
# Provides: aattd
# Required-Start: mysql $network
# Required-Stop:
# Short-Description: aattd server
# Description: Automate All The Things Server Daemon
### END INIT INFO

# Source function library
. /etc/rc.d/init.d/functions

INITLOG_ARGS=""

aattd=/opt/aatt/server.py
prog=aattd
pidfile=/var/run/aatt/aattd.pid
lockfile=/var/lock/subsys/aattd
RETVAL=0

start() {
		echo -n $"Starting $prog: "
		$aattd &
		RETVAL=$?
		echo
		[ $RETVAL = 0 ] && touch ${lockfile}
		return $RETVAL
	}

stop() {
		echo -n $"Stopping $prog: "
		killproc $aattd
		RETVAL=$?
		echo
		[ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
	}

reload() {
    echo -n $"Reloading $prog: "
    if ! $aattd $OPTIONS -t >&/dev/null; then
        RETVAL=6
        echo $"not reloading due to configuration syntax error"
        failure $"not reloading $httpd due to configuration syntax error"
    else
        # Force LSB behaviour from killproc
        LSB=1 killproc -p ${pidfile} $aattd -HUP
        RETVAL=$?
        if [ $RETVAL -eq 7 ]; then
            failure $"aattd shutdown"
        fi
    fi
    echo
}

# See how we were called.
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
        status -p ${pidfile} $aattd
    RETVAL=$?
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo $"Usage: $prog {start|stop|restart|status}"
    RETVAL=2
esac

exit $RETVAL

